# Generated by Django 4.2.6 on 2023-10-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.JSONField(default=[[None, None, None], [None, None, None], [None, None, None]])),
                ('winner', models.CharField(blank=True, max_length=255, null=True)),
                ('movements_played', models.IntegerField(default=0)),
                ('next_turn', models.CharField(max_length=255)),
                ('players', models.ManyToManyField(related_name='games', to='tictactoe.player')),
            ],
        ),
    ]
